---
title: "Marketing Analytics"
listing: 
  contents: listings
  type: grid
  categories: true
  sort: 
    - "index desc"
---

In my journey as a marketing analyst, I have consistently transformed complex marketing data into clear, actionable insights, driving informed decisions and tangible business results. My experience spans a wide range of analytical techniques, including predictive modeling, pricing analysis, segmentation, and campaign performance evaluation. These projects reflect my ability to seamlessly integrate statistical tools, data visualization, and strategic thinking to solve real-world marketing challenges.


I specialize in uncovering consumer insights, optimizing pricing strategies, and evaluating marketing effectiveness, always focused on turning data into a competitive advantage. Below are selected projects that showcase my expertise in marketing analytics.

## What You’ll Find

-   **Consumer Behavior Analysis**: Identified key drivers of customer loyalty for Baskin-Robbins using regression and chi-square tests.
-   **Pricing Optimization**: Assessed consumer willingness to pay for Netflix plans using Van Westendorp, Gabor-Granger, and Conjoint Analysis.
-   **Customer Segmentation**: Developed customer personas through cluster analysis, revealing high-value and low-value segments.
-   **Campaign Performance Evaluation**: Measured digital marketing effectiveness using interactive dashboards for real-time insights.
-   **SEO & Web Analytics**: Improved website visibility and user engagement through data-driven SEO strategies.

------------------------------------------------------------------------
